//! Core trait and data types for the deployment provider abstraction.
//!
//! Every cloud/edge target in the gateway implements `DeployProvider`.  This module
//! defines the shared vocabulary — configuration structs, deployment records, status
//! enums, and credential containers — that all adapters agree on.
//!
//! ## Key dependencies
//!
//! * `async_trait` — because Rust traits cannot yet declare async methods natively.
//! * `serde` — all config types are serializable so they can cross API boundaries.
//! * `clawz_core::error` — unified `Result` and `ClawzError` types.

use async_trait::async_trait;
use clawz_core::error::Result;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Trait that every deployment target must implement.
///
/// Adapters are expected to be stateless w.r.t. deployment records; they talk to
/// live APIs and return metadata.  The `DeployManager` (in `mod.rs`) handles
/// persistence via `DeploymentStore`.
#[async_trait]
pub trait DeployProvider: Send + Sync {
    /// Canonical short identifier used as a HashMap key, e.g. `"fly_io"`.
    fn provider_id(&self) -> &str;
    /// Human-readable name for dashboards and CLI output, e.g. `"Fly.io"`.
    fn display_name(&self) -> &str;
    /// Which `DeployMode` variants this provider can accept.
    fn supported_modes(&self) -> Vec<DeployMode>;
    /// Check that the supplied credentials can authenticate with the provider API.
    async fn validate_credentials(&self, creds: &ProviderCredentials) -> Result<()>;
    /// Begin a deployment and return initial metadata (URL, ID, pending status).
    async fn deploy(&self, config: &DeployConfig) -> Result<DeploymentInfo>;
    /// Poll the provider for the current liveness of a deployment.
    async fn status(&self, id: &str) -> Result<DeploymentStatus>;
    /// Tear down the named deployment on the provider side.
    async fn destroy(&self, id: &str) -> Result<()>;
}

/// Deployment payload type requested by the user.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DeployMode {
    /// Run a Docker image (name must be supplied by the caller).
    Docker { image: String },
    /// Run a native binary compiled for the target architecture.
    NativeBinary,
    /// Run a WebAssembly module (used by edge platforms such as Fastly / Cloudflare).
    Wasm,
}

/// User-supplied deployment configuration passed to `DeployProvider::deploy`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployConfig {
    /// Which payload format to deploy.
    pub mode: DeployMode,
    /// Key-value environment variables injected into the runtime.
    pub env_vars: HashMap<String, String>,
    /// Optional provider-specific region or datacenter identifier.
    pub region: Option<String>,
    /// Desired replica count (honored by container platforms and Kubernetes).
    pub replicas: u32,
}

/// Snapshot of a deployment after `deploy` returns.
///
/// The `id` is generated by the gateway; the `url` is the provider's public
/// endpoint (or invocation URL for serverless targets).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeploymentInfo {
    /// Unique deployment identifier assigned by the gateway.
    pub id: String,
    /// Publicly reachable URL or invocation endpoint.
    pub url: String,
    /// Last-known status (initially `Pending`).
    pub status: DeploymentStatus,
}

/// Lifecycle states a deployment can occupy.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum DeploymentStatus {
    /// Deployment request has been accepted but the provider has not confirmed readiness.
    Pending,
    /// Provider reports the deployment is healthy and reachable.
    Running,
    /// Explicitly stopped or destroyed via `destroy()`.
    Stopped,
    /// Provider reports the deployment is in a failed or errored state.
    Failed,
}

/// Credential bag passed to `validate_credentials` and underlying API calls.
///
/// Not all fields are used by every provider; unused fields are ignored.
/// The `extra` map holds provider-specific tokens (e.g. Azure `tenant_id`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderCredentials {
    /// Bearer or personal access token (Cloudflare, Fly.io, Railway, etc.).
    pub api_token: Option<String>,
    /// Public API key (AWS access key, Oracle API key, Azure client ID).
    pub api_key: Option<String>,
    /// Secret counterpart to `api_key` (AWS secret key, Azure client secret).
    pub api_secret: Option<String>,
    /// Project or compartment identifier (GCP project, Northflank project).
    pub project_id: Option<String>,
    /// Default region override (used when `DeployConfig::region` is `None`).
    pub region: Option<String>,
    /// Free-form key-value map for provider-specific secrets (tenant IDs, compartment IDs, etc.).
    pub extra: HashMap<String, String>,
}

impl Default for ProviderCredentials {
    fn default() -> Self {
        Self {
            api_token: None,
            api_key: None,
            api_secret: None,
            project_id: None,
            region: None,
            extra: HashMap::new(),
        }
    }
}
