[package]
name = "clawz-core"
version = "1.1.0"
edition = "2021"
license = "Elastic-2.0"
rust-version = "1.75"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true, optional = true }
base64 = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
futures-core = { workspace = true }
http = { workspace = true }
sqlx = { workspace = true }
parking_lot = { workspace = true, optional = true }
clawz-platform = { path = "../clawz-platform", version = "1.1.0" }

[features]
default = ["std"]
std = ["dep:parking_lot", "dep:uuid"]
t0 = []
t1 = ["tokio/rt"]
t2 = ["tokio/rt", "dep:parking_lot"]
t3 = ["tokio/rt-multi-thread", "dep:parking_lot"]
tauri = ["tokio/rt"]
