//! Versioned skill repository for skill.md / soul.md / agents.md lifecycle.
//!
//! File-based provisioning at container deploy time; agent runtime updates
//! take precedence (versioned). Generated skill.md includes `agentskills.io`
//! header comment for discovery compatibility.

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;
use tokio::sync::RwLock;

use clawz_core::error::{ClawzError, Result};

/// A complete skill bundle for one agent container.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillBundle {
    /// The skill.md content.
    pub skill_md: String,
    /// The soul.md content.
    pub soul_md: String,
    /// The agents.md content.
    pub agents_md: String,
    /// Monotonically increasing version; agent updates are always newer.
    pub version: u64,
    /// Where this bundle originated.
    pub source: SkillSource,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SkillSource {
    /// Provisioned from filesystem at container deploy time.
    File,
    /// Updated by the agent at runtime.
    Agent,
    /// Merged from multiple sources (future).
    Merged,
}

/// Trait for skill repository backends.
#[async_trait]
pub trait SkillRepository: Send + Sync {
    async fn get_skill(&self, agent_id: &str) -> Result<Option<SkillBundle>>;
    async fn update_skill(&self, agent_id: &str, bundle: SkillBundle) -> Result<()>;
}

/// Versioned skill repository with file-based provisioning and agent runtime updates.
pub struct VersionedSkillRepository {
    base_path: std::path::PathBuf,
    file_provisions: HashMap<String, SkillBundle>,
    agent_updates: RwLock<HashMap<String, SkillBundle>>,
}

impl VersionedSkillRepository {
    /// Provision a new agent from its container's filesystem layout.
    ///
    /// Looks for `skill.md`, `soul.md`, and `agents.md` alongside `base_path`.
    pub fn provision(agent_id: &str, base_path: &Path) -> Result<Self> {
        let skill_md = std::fs::read_to_string(base_path.join("skill.md"))
            .map_err(|e| ClawzError::Internal(format!("skill.md: {e}")))?;
        let soul_md = std::fs::read_to_string(base_path.join("soul.md"))
            .map_err(|e| ClawzError::Internal(format!("soul.md: {e}")))?;
        let agents_md = std::fs::read_to_string(base_path.join("agents.md"))
            .map_err(|e| ClawzError::Internal(format!("agents.md: {e}")))?;

        let bundle = SkillBundle {
            skill_md,
            soul_md,
            agents_md,
            version: 1,
            source: SkillSource::File,
        };
        let mut provisions = HashMap::new();
        provisions.insert(agent_id.to_string(), bundle);

        Ok(Self {
            base_path: base_path.to_path_buf(),
            file_provisions: provisions,
            agent_updates: RwLock::new(HashMap::new()),
        })
    }

    /// Retrieve the current skill bundle for an agent.
    ///
    /// Agent runtime updates take precedence over file provisions.
    pub async fn get_skill(&self, agent_id: &str) -> Result<Option<SkillBundle>> {
        let agent_update = self.agent_updates.read().await.get(agent_id).cloned();
        if let Some(bundle) = agent_update {
            return Ok(Some(bundle));
        }
        Ok(self.file_provisions.get(agent_id).cloned())
    }

    /// Record an agent-authored update to its skill bundle.
    ///
    /// Agent updates always win — they replace whatever was provisioned.
    pub async fn update_skill(&self, agent_id: &str, bundle: SkillBundle) -> Result<()> {
        let mut updates = self.agent_updates.write().await;
        updates.insert(agent_id.to_string(), bundle);
        Ok(())
    }
}

impl SkillBundle {
    /// Generate skill.md in agentskills.io-compatible format.
    ///
    /// The `<!-- agentskills.io -->` comment enables discovery via the
    /// agentskills.io registry.
    pub fn generate_skill_md(role: &str, skills: &[&str], principles: &[&str]) -> Self {
        let skill_md = format!(
            "# <!-- agentskills.io --> Skill: {}\n\n## Capabilities\n{}\n\n## Principles\n{}\n",
            role,
            skills.iter().map(|s| format!("- {}", s)).collect::<Vec<_>>().join("\n"),
            principles.iter().map(|p| format!("- {}", p)).collect::<Vec<_>>().join("\n"),
        );
        let soul_md = format!(
            "# Soul: {}\n\n## Operating Principles\n{}\n",
            role,
            principles.iter().map(|p| format!("- {}", p)).collect::<Vec<_>>().join("\n"),
        );
        let agents_md = "# Agents\n\nGenerated by ClawZ skill synthesis pipeline.".to_string();
        Self { skill_md, soul_md, agents_md, version: 1, source: SkillSource::Agent }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn skill_repo_provisions_from_filesystem() {
        let temp = tempfile::tempdir().unwrap();
        std::fs::write(temp.path().join("skill.md"), "# Skill\nRole: developer").unwrap();
        std::fs::write(temp.path().join("soul.md"), "# Soul\nPrinciple: ship it").unwrap();
        std::fs::write(temp.path().join("agents.md"), "# Agents\nDesign, Dev, Test").unwrap();

        let repo = VersionedSkillRepository::provision("agent-1", temp.path()).unwrap();
        let bundle = repo.get_skill("agent-1").await.unwrap().unwrap();
        assert!(bundle.skill_md.contains("developer"));
        assert!(bundle.soul_md.contains("ship it"));
        assert_eq!(bundle.source, SkillSource::File);
    }

    #[tokio::test]
    async fn skill_repo_agent_update_takes_precedence() {
        let temp = tempfile::tempdir().unwrap();
        std::fs::write(temp.path().join("skill.md"), "# Skill v1").unwrap();
        std::fs::write(temp.path().join("soul.md"), "# Soul").unwrap();
        std::fs::write(temp.path().join("agents.md"), "# Agents").unwrap();

        let repo = VersionedSkillRepository::provision("agent-1", temp.path()).unwrap();
        let updated = SkillBundle {
            skill_md: "# Skill v2 (updated by agent)".into(),
            soul_md: "# Soul".into(),
            agents_md: "# Agents".into(),
            version: 2,
            source: SkillSource::Agent,
        };
        repo.update_skill("agent-1", updated).await.unwrap();

        let bundle = repo.get_skill("agent-1").await.unwrap().unwrap();
        assert!(bundle.skill_md.contains("v2"));
        assert_eq!(bundle.source, SkillSource::Agent);
    }

    #[tokio::test]
    async fn skill_repo_agentskills_compatible_format() {
        let bundle = SkillBundle::generate_skill_md(
            "developer",
            &["Rust", "Tokio", "Async"],
            &["quality", "speed"],
        );
        assert!(bundle.skill_md.contains("developer"));
        assert!(bundle.skill_md.contains("agentskills.io"));
        assert!(bundle.soul_md.contains("Operating Principles"));
    }
}